import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "Aron",
    lastName: "James",
    username: "aron20",
    password: "aron123",
    bookmarks: [],
    bio: 'Specialized in mobile and web products',
    website: ' https://www.aaronjames.design/',
    avatar: 'https://images.unsplash.com/photo-1601233749202-95d04d5b3c00?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8MHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Varnita",
    lastName: "Makrariya",
    username: "varnita19",
    password: "varnita123",
    bookmarks: [],
    bio: 'Aspring FullStack Developer',
    website: ' https://varnitamakrariya.netlify.app/',
    avatar: 'https://images.unsplash.com/photo-1601233749202-95d04d5b3c00?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8MHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Samyak",
    lastName: "Shah",
    username: "samyakshah",
    password: "samyak123",
    bookmarks: [],
    bio: 'Aspring FullStack Developer',
    website: ' https://varnitamakrariya.netlify.app/',
    avatar: 'https://images.unsplash.com/photo-1601233749202-95d04d5b3c00?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8MHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Pritam",
    lastName: "Kumar",
    username: "pritamkumar",
    password: "pritam123",
    bookmarks: [],
    bio: 'Aspring FullStack Developer',
    website: ' https://varnitamakrariya.netlify.app/',
    avatar: 'https://images.unsplash.com/photo-1601233749202-95d04d5b3c00?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8MHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Anuj",
    lastName: "Kumar",
    username: "anujkumar",
    password: "anuj123",
    bookmarks: [],
    bio: 'Aspring FullStack Developer',
    website: ' https://varnitamakrariya.netlify.app/',
    avatar: 'https://images.unsplash.com/photo-1601233749202-95d04d5b3c00?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8MHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "John",
    lastName: "Human",
    username: "johnthehuman",
    password: "john123",
    bookmarks: [],
    bio: 'Graphic Designer',
    website: ' https://johnthehuman.com/',
    avatar: 'https://images.unsplash.com/photo-1601233749202-95d04d5b3c00?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8MHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
